[theme]
base = "light"
primaryColor = "#8A5A36"
backgroundColor = "#FCFAF6"
secondaryBackgroundColor = "#F3ECE1"
textColor = "#2D241B"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
